# Generated by Django 5.0.3 on 2024-04-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors')),
                ('sub_descriptions', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=100, null=True)),
                ('language_use', models.CharField(blank=True, max_length=100, null=True)),
                ('about_for_instructor', models.TextField(blank=True, null=True)),
                ('social_media_facebook', models.URLField(blank=True, null=True)),
                ('social_media_twitter', models.URLField(blank=True, null=True)),
                ('social_media_youtube', models.URLField(blank=True, null=True)),
                ('social_media_instagram', models.URLField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='instructors', to='courses.course')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'Teachers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.CharField(blank=True, max_length=200, null=True)),
                ('courses_enrolled', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
