# Generated by Django 5.0.3 on 2024-04-06 21:22

import utils.generate_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=10),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=10),
        ),
    ]
