# Generated by Django 5.0.3 on 2024-04-08 19:52

import utils.generate_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructor_profile_code_student_profile_code'),
        ('courses', '0002_alter_course_description_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='courses_enrolled',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors')),
                ('sub_descriptions', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=100, null=True)),
                ('language_use', models.CharField(blank=True, max_length=100, null=True)),
                ('about_for_instructor', models.TextField(blank=True, null=True)),
                ('social_media_facebook', models.URLField(blank=True, null=True)),
                ('social_media_twitter', models.URLField(blank=True, null=True)),
                ('social_media_youtube', models.URLField(blank=True, null=True)),
                ('social_media_instagram', models.URLField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='instructors', to='courses.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Instructor_Profile',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
