# Generated by Django 5.0.3 on 2024-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_us',
            field=models.TextField(),
        ),
    ]
