# Generated by Django 5.0.3 on 2024-04-04 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_description', models.TextField(blank=True, max_length=3000, null=True)),
                ('duration', models.DurationField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('veido', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('resources', models.FileField(blank=True, null=True, upload_to='lesson_resources/')),
                ('assignment', models.BooleanField(default=False)),
                ('slides', models.FileField(blank=True, null=True, upload_to='lesson_slides/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='courses.course')),
                ('instructor', models.ForeignKey(limit_choices_to={'groups__name': 'Teachers'}, on_delete=django.db.models.deletion.CASCADE, related_name='instractor_lesson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
