# Generated by Django 5.0.3 on 2024-04-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_course', to='courses.course')),
            ],
        ),
    ]
