# Generated by Django 5.0.3 on 2024-04-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='veido',
            new_name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_unit', to='courses.unit'),
            preserve_default=False,
        ),
    ]
