# Generated by Django 5.0.3 on 2024-04-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_instructor_course_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='Course',
            new_name='course',
        ),
    ]
