# Generated by Django 5.0.3 on 2024-10-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_instructor_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
    ]
