# Generated by Django 5.0.3 on 2024-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatelog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activatelog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activatelog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
