# Generated by Django 5.0.3 on 2024-07-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0002_activatelog_city_activatelog_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activatelog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='activatelog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='activatelog',
            name='region',
        ),
    ]
