# Generated by Django 5.0.3 on 2024-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderdetail_total_cart_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetial',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='FEN1ENGB', max_length=9),
        ),
    ]
