# Generated by Django 5.0.3 on 2024-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_instructor_notification'),
        ('orders', '0005_cartdetial_total_alter_order_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartDetial',
            new_name='CartDetail',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='YLP4QQ6H', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], default='InProgress', max_length=10),
        ),
    ]
