# Generated by Django 5.0.3 on 2024-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_instructor_notification'),
        ('orders', '0006_rename_cartdetial_cartdetail_alter_cart_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartDetail',
            new_name='CartDetial',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='3YPX78XS', max_length=9),
        ),
    ]
