# Generated by Django 5.0.3 on 2024-07-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cart_status_alter_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='EWC0XCL3', max_length=9),
        ),
    ]
