# Generated by Django 5.0.3 on 2024-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('InProgress', 'InProgress')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='KQTL9LLA', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('InProgress', 'InProgress')], default='InProgress', max_length=10),
        ),
    ]
